services:
  - type: web
    name: tal-chess-academy
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn tal_academy.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.7"
