"""
Django settings for tal_academy project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a local .env file into the environment. This is a
# no-op if .env doesn't exist, which is the case on most production hosts,
# where env vars are injected directly by the platform instead.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# DEBUG defaults to False — a missing/misconfigured env var should fail safe
# (closed) rather than fail open into exposing stack traces and settings.
# Set DEBUG=True explicitly in .env for local development.
DEBUG = os.getenv('DEBUG', 'False').strip().lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# Always supplied via the SECRET_KEY env var (see .env.example).
# In production (DEBUG=False) we refuse to start rather than silently fall
# back to an insecure, publicly-committed default key.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-z_5t(5#ll+ta+-mg_-(!48jr2ztaml*)-p7or&2-9vbbgfvd!b'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable must be set when DEBUG is False. '
            'Refusing to start with an insecure default key in production.'
        )

ALLOWED_HOSTS = []
_extra_hosts = os.getenv('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [host.strip() for host in _extra_hosts.split(',') if host.strip()]

# Derived from ALLOWED_HOSTS rather than hardcoded to any one host's
# auto-injected hostname variable, so this works the same on any platform.
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '.ngrok-free.dev', '.ngrok-free.app', '.ngrok.io', '.ngrok.app']
    CSRF_TRUSTED_ORIGINS += [
        'https://*.ngrok-free.dev', 'https://*.ngrok-free.app', 'https://*.ngrok.io', 'https://*.ngrok.app'
    ]

# Most PaaS hosts and reverse proxies terminate TLS at the proxy and forward
# plain HTTP, so trust their header to know when a request was actually HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    # Safe, reversible hardening — assumes production is always served over
    # HTTPS, which it should be. HSTS is deliberately left off: browsers
    # cache it for the duration you set, which makes it awkward to undo if
    # something's misconfigured. Turn it on once HTTPS is confirmed stable:
    #   SECURE_HSTS_SECONDS = 31536000
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# The admin path, kept out of the well-known "/admin/" default as one cheap
# layer of defense-in-depth against automated scanners. Change it via env
# var if you want a different one — used in tal_academy/urls.py.
ADMIN_URL = os.getenv('ADMIN_URL', 'staff-portal/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'rest_framework',
    'axes',
    'academy',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'academy.middleware.NoIndexAdminApiMiddleware',
]

# django-axes needs its own backend checked first to enforce lockouts.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'tal_academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tal_academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Uses DATABASE_URL when set (e.g. a managed Postgres instance); otherwise
# falls back to a local SQLite file, which is fine for development.

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # conn_health_checks: managed Postgres providers periodically drop idle
    # connections; without this, Django can hand out a dead connection from
    # its pool and error on the next request that uses it.
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Leaving EMAIL_HOST blank (the default) sends email to the console instead
# of over SMTP — handy for local development without a real mail account.
# Set EMAIL_HOST (and the other EMAIL_* vars) in .env to send real email.

EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').strip().lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@talchessacademy.example')

# Emails are sent synchronously inside the request (see academy/emails.py).
# Without a timeout, a slow/unreachable SMTP server hangs that request until
# gunicorn's own worker timeout kills it — a bad connection should fail fast
# instead of stalling the response to whoever just submitted a form.
EMAIL_TIMEOUT = 10

# Not a built-in Django setting — our own, read by academy/emails.py to know
# where to send new-submission notifications.
ACADEMY_NOTIFICATION_EMAIL = os.getenv('ACADEMY_NOTIFICATION_EMAIL', DEFAULT_FROM_EMAIL)

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Not a built-in Django setting — our own, read by
# `manage.py purge_old_submissions`. Deliberately no default: we're not
# asserting a specific retention period applies here, so the command is a
# no-op until you explicitly decide on one and set this.
SUBMISSION_RETENTION_DAYS = os.getenv('SUBMISSION_RETENTION_DAYS')
if SUBMISSION_RETENTION_DAYS:
    SUBMISSION_RETENTION_DAYS = int(SUBMISSION_RETENTION_DAYS)
else:
    SUBMISSION_RETENTION_DAYS = None

# Django emails these addresses automatically whenever an unhandled 500
# happens in production (via the mail_admins log handler wired up by
# Django's own default logging config) — otherwise a real crash for a real
# visitor would go completely unnoticed unless someone happened to check
# the server logs.
if ACADEMY_NOTIFICATION_EMAIL:
    ADMINS = [('Site Admin', ACADEMY_NOTIFICATION_EMAIL)]
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
# Public write endpoints (registrations, contact) are rate-limited per IP to
# blunt basic spam/abuse; the read-only programs list gets a more generous cap.

REST_FRAMEWORK = {
    # Most PaaS hosts (and the ngrok dev tunnel) sit exactly one proxy hop in
    # front of the app. Without this, DRF trusts the client-supplied
    # X-Forwarded-For header verbatim, which lets a client spoof a different
    # "identity" on every request and bypass the throttles below entirely.
    'NUM_PROXIES': 1,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',
        'registration': '5/hour',
        'contact': '10/hour',
    },
    # Secure by default: any future view that forgets to set permission_classes
    # is private, not public. The three current public endpoints opt in to
    # AllowAny explicitly (see academy/api_views.py).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Drop BasicAuthentication (DRF's default) — nothing here uses it, and it
    # sends credentials on every request rather than a scoped token/session.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # The interactive Browsable API is handy for local testing (see README)
    # but reveals framework internals to anyone who browses to an API URL
    # directly — restrict production to plain JSON only.
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer']
        if not DEBUG
        else ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer']
    ),
}


# django-axes: locks out repeated failed login attempts against /staff-portal/
# (and anywhere else using Django's auth backends). Without this, admin login
# has no brute-force protection at all — Django ships none by default.
# https://django-axes.readthedocs.io/

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
# Matches REST_FRAMEWORK['NUM_PROXIES'] above — same single-proxy topology.
AXES_IPWARE_PROXY_COUNT = 1


# Logging
# Ensures email-send failures (caught in academy/emails.py) are actually
# visible in the console/server logs instead of silently disappearing.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
