# Generated by Django 6.1 on 2026-08-11 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, +, -, and parentheses only).', regex='^[0-9+\\-()\\s]{7,20}$')])),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — never shown to the sender.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(choices=[('junior', 'Junior'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('private', 'Private Coaching')], max_length=20)),
                ('age_group', models.CharField(help_text='e.g. "Ages 6–11" or "1200+ rated"', max_length=60)),
                ('duration', models.CharField(blank=True, help_text='e.g. "12-week term"', max_length=60)),
                ('icon', models.CharField(choices=[('pawn', 'Pawn'), ('knight', 'Knight'), ('bishop', 'Bishop'), ('rook', 'Rook'), ('queen', 'Queen'), ('king', 'King')], default='pawn', max_length=20)),
                ('cta_label', models.CharField(default='View curriculum', max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive programs are hidden from the site and API.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('parent_name', models.CharField(blank=True, help_text='Leave blank for adult students registering themselves.', max_length=120)),
                ('student_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, +, -, and parentheses only).', regex='^[0-9+\\-()\\s]{7,20}$')])),
                ('email', models.EmailField(max_length=254)),
                ('chess_level', models.CharField(choices=[('none', 'Never played'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='none', max_length=20)),
                ('preferred_schedule', models.CharField(blank=True, help_text="Preferred days/times, in the applicant's own words.", max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial Scheduled'), ('enrolled', 'Enrolled'), ('closed', 'Rejected / Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — never shown to the applicant.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academy.program')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
