# Generated by Django 6.1 on 2026-08-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_program_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price_in_person',
            field=models.PositiveIntegerField(blank=True, help_text='PKR for one face-to-face session. Leave blank if there is no single published rate.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='price_online',
            field=models.PositiveIntegerField(blank=True, help_text='PKR for one online session. Leave blank if there is no single published rate.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Length of one session, in minutes — the unit both prices above refer to.'),
        ),
        migrations.AddField(
            model_name='trialregistration',
            name='session_format',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('in_person', 'Face-to-face')], help_text='Whether the enquirer asked about online or face-to-face sessions.', max_length=20),
        ),
    ]
